name: CI/CD com Docker

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Instalar dependências
        run: |
          pip install -r app/requirements.txt

      - name: Rodar testes (simples)
        run: |
          python -c "import requests; print('Testando aplicação Flask')"

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir e enviar imagem Docker
        run: |
          docker build -t meu_usuario_docker/meuapp:latest .
          docker push meu_usuario_docker/meuapp:latest

      - name: Deploy no servidor
        run: |
          ssh user@meuservidor.com 'docker pull meu_usuario_docker/meuapp:latest && docker-compose up -d'
